# Generated by Django 2.2.4 on 2019-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogarticles_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
